Revert "Set up publication of PR final artifacts to artifactory-online."
This reverts commit 1f2d8e95e9b4d97a851985f4a9a5235379c7373c.

IT caused

java.lang.NumberFormatException: There was a problem parsing 2.11.075ecb44. Versions should be in the form major[.minor[.revision]] where each part is a positive number, as in 2.10.1. The minor and revision parts are optional.
	at scala.tools.nsc.settings.ScalaVersion$$anonfun$apply$1.apply(ScalaVersion.scala:113)