hack to let sbt document a project that's a dependency of scaladoc
the doc task fails with java.lang.NoClassDefFoundError: scala/xml/NamespaceBinding
when documenting scala-xml 1.0.0, where scaladoc depends on scala-xml 1.0.0,
even if all required jars are available through the project's resolvers

sbt won't look past this project -- I tried doing a publish-local without docs
(set publishArtifact in (Compile, packageDoc) := false) and then calling `doc`,
but it still fails

SOOOOO, we set the version to a dummy (1.0.0-DOC), generate documentation
(which then lets sbt resolve the required jars externally), THEN
set the version to the right one and publish (which won't re-gen the docs)